# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QITKV0p9.ui'
#
# Created: Wed Aug  5 10:06:38 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1277, 741)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget_image = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_image.sizePolicy().hasHeightForWidth())
        self.stackedWidget_image.setSizePolicy(sizePolicy)
        self.stackedWidget_image.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget_image.setObjectName(_fromUtf8("stackedWidget_image"))
        self.Image_page1 = QtGui.QWidget()
        self.Image_page1.setObjectName(_fromUtf8("Image_page1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Image_page1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.spinBox_p1_Scroll = QtGui.QSpinBox(self.Image_page1)
        self.spinBox_p1_Scroll.setMinimum(1)
        self.spinBox_p1_Scroll.setMaximum(10)
        self.spinBox_p1_Scroll.setObjectName(_fromUtf8("spinBox_p1_Scroll"))
        self.gridLayout_6.addWidget(self.spinBox_p1_Scroll, 1, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 4, 1, 1)
        self.spinBox_x_3panel = QtGui.QSpinBox(self.Image_page1)
        self.spinBox_x_3panel.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_x_3panel.setSuffix(_fromUtf8(""))
        self.spinBox_x_3panel.setPrefix(_fromUtf8("x: "))
        self.spinBox_x_3panel.setObjectName(_fromUtf8("spinBox_x_3panel"))
        self.gridLayout_6.addWidget(self.spinBox_x_3panel, 1, 0, 1, 1)
        self.spinBox_y_3panel = QtGui.QSpinBox(self.Image_page1)
        self.spinBox_y_3panel.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_y_3panel.setPrefix(_fromUtf8("y: "))
        self.spinBox_y_3panel.setObjectName(_fromUtf8("spinBox_y_3panel"))
        self.gridLayout_6.addWidget(self.spinBox_y_3panel, 1, 1, 1, 1)
        self.spinBox_v_3panel = QtGui.QSpinBox(self.Image_page1)
        self.spinBox_v_3panel.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_v_3panel.setObjectName(_fromUtf8("spinBox_v_3panel"))
        self.gridLayout_6.addWidget(self.spinBox_v_3panel, 1, 3, 1, 1)
        self.spinBox_z_3panel = QtGui.QSpinBox(self.Image_page1)
        self.spinBox_z_3panel.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_z_3panel.setPrefix(_fromUtf8("z: "))
        self.spinBox_z_3panel.setObjectName(_fromUtf8("spinBox_z_3panel"))
        self.gridLayout_6.addWidget(self.spinBox_z_3panel, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 6, 1, 1)
        self.frame_3panels = QtGui.QFrame(self.Image_page1)
        self.frame_3panels.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3panels.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3panels.setLineWidth(0)
        self.frame_3panels.setObjectName(_fromUtf8("frame_3panels"))
        self.gridLayout_6.addWidget(self.frame_3panels, 0, 0, 1, 7)
        self.stackedWidget_image.addWidget(self.Image_page1)
        self.Image_page2 = QtGui.QWidget()
        self.Image_page2.setObjectName(_fromUtf8("Image_page2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Image_page2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.SliderFrame = QtGui.QFrame(self.Image_page2)
        self.SliderFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SliderFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SliderFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.SliderFrame.setObjectName(_fromUtf8("SliderFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.SliderFrame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_z_2panel = QtGui.QLineEdit(self.SliderFrame)
        self.lineEdit_z_2panel.setMinimumSize(QtCore.QSize(45, 0))
        self.lineEdit_z_2panel.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lineEdit_z_2panel.setAutoFillBackground(True)
        self.lineEdit_z_2panel.setFrame(True)
        self.lineEdit_z_2panel.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_z_2panel.setObjectName(_fromUtf8("lineEdit_z_2panel"))
        self.horizontalLayout.addWidget(self.lineEdit_z_2panel)
        self.horizontalScrollBar_z_2panel = QtGui.QScrollBar(self.SliderFrame)
        self.horizontalScrollBar_z_2panel.setMinimumSize(QtCore.QSize(300, 0))
        self.horizontalScrollBar_z_2panel.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_z_2panel.setObjectName(_fromUtf8("horizontalScrollBar_z_2panel"))
        self.horizontalLayout.addWidget(self.horizontalScrollBar_z_2panel)
        self.spinBox_v_2panel = QtGui.QSpinBox(self.SliderFrame)
        self.spinBox_v_2panel.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_v_2panel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_v_2panel.setObjectName(_fromUtf8("spinBox_v_2panel"))
        self.horizontalLayout.addWidget(self.spinBox_v_2panel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.spinBox_P2_scroll = QtGui.QSpinBox(self.SliderFrame)
        self.spinBox_P2_scroll.setMinimum(1)
        self.spinBox_P2_scroll.setMaximum(10)
        self.spinBox_P2_scroll.setObjectName(_fromUtf8("spinBox_P2_scroll"))
        self.horizontalLayout.addWidget(self.spinBox_P2_scroll)
        self.gridLayout_3.addWidget(self.SliderFrame, 1, 0, 1, 2)
        self.frame_2panels = QtGui.QFrame(self.Image_page2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.frame_2panels.setPalette(palette)
        self.frame_2panels.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2panels.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2panels.setObjectName(_fromUtf8("frame_2panels"))
        self.gridLayout_3.addWidget(self.frame_2panels, 0, 0, 1, 2)
        self.lineEdit_console = QtGui.QLineEdit(self.Image_page2)
        self.lineEdit_console.setObjectName(_fromUtf8("lineEdit_console"))
        self.gridLayout_3.addWidget(self.lineEdit_console, 2, 0, 1, 2)
        self.stackedWidget_image.addWidget(self.Image_page2)
        self.Image_page3 = QtGui.QWidget()
        self.Image_page3.setObjectName(_fromUtf8("Image_page3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.Image_page3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.stackedWidget_image.addWidget(self.Image_page3)
        self.gridLayout_2.addWidget(self.stackedWidget_image, 0, 1, 1, 1)
        self.stackedWidget_control = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget_control.setMaximumSize(QtCore.QSize(300, 16777215))
        self.stackedWidget_control.setObjectName(_fromUtf8("stackedWidget_control"))
        self.Control_page1 = QtGui.QWidget()
        self.Control_page1.setObjectName(_fromUtf8("Control_page1"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Control_page1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 7, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.Control_page1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_7.addWidget(self.pushButton, 2, 0, 1, 1)
        self.ProcessPhase = QtGui.QPushButton(self.Control_page1)
        self.ProcessPhase.setObjectName(_fromUtf8("ProcessPhase"))
        self.gridLayout_7.addWidget(self.ProcessPhase, 2, 1, 1, 1)
        self.QSM = QtGui.QPushButton(self.Control_page1)
        self.QSM.setObjectName(_fromUtf8("QSM"))
        self.gridLayout_7.addWidget(self.QSM, 3, 0, 1, 1)
        self.toolBox = QtGui.QToolBox(self.Control_page1)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 520))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 278, 458))
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout = QtGui.QFormLayout(self.page)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.radioButton_left = QtGui.QRadioButton(self.page)
        self.radioButton_left.setChecked(False)
        self.radioButton_left.setObjectName(_fromUtf8("radioButton_left"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.radioButton_left)
        self.treeWidget = QtGui.QTreeWidget(self.page)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 370))
        self.treeWidget.setAutoScroll(True)
        self.treeWidget.setAutoScrollMargin(16)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setDefaultSectionSize(120)
        self.treeWidget.header().setMinimumSectionSize(33)
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.treeWidget)
        self.radioButton_right = QtGui.QRadioButton(self.page)
        self.radioButton_right.setChecked(True)
        self.radioButton_right.setObjectName(_fromUtf8("radioButton_right"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.radioButton_right)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 278, 458))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.treeWidget_parameters = QtGui.QTreeWidget(self.page_2)
        self.treeWidget_parameters.setIndentation(16)
        self.treeWidget_parameters.setRootIsDecorated(True)
        self.treeWidget_parameters.setObjectName(_fromUtf8("treeWidget_parameters"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_parameters)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_parameters)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.gridLayout_9.addWidget(self.treeWidget_parameters, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.toolBox, 0, 0, 2, 2)
        self.stackedWidget_control.addWidget(self.Control_page1)
        self.Control_Page2 = QtGui.QWidget()
        self.Control_Page2.setObjectName(_fromUtf8("Control_Page2"))
        self.gridLayout = QtGui.QGridLayout(self.Control_Page2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.Control_Page2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.doubleSpinBox_mid = QtGui.QDoubleSpinBox(self.Control_Page2)
        self.doubleSpinBox_mid.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_mid.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_mid.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_mid.setObjectName(_fromUtf8("doubleSpinBox_mid"))
        self.gridLayout.addWidget(self.doubleSpinBox_mid, 7, 1, 1, 1)
        self.doubleSpinBox_max = QtGui.QDoubleSpinBox(self.Control_Page2)
        self.doubleSpinBox_max.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_max.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_max.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_max.setObjectName(_fromUtf8("doubleSpinBox_max"))
        self.gridLayout.addWidget(self.doubleSpinBox_max, 4, 3, 1, 1)
        self.pushButton_opened = QtGui.QPushButton(self.Control_Page2)
        self.pushButton_opened.setObjectName(_fromUtf8("pushButton_opened"))
        self.gridLayout.addWidget(self.pushButton_opened, 15, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.Control_Page2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.radio_left = QtGui.QRadioButton(self.Control_Page2)
        self.radio_left.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radio_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radio_left.setChecked(True)
        self.radio_left.setObjectName(_fromUtf8("radio_left"))
        self.gridLayout.addWidget(self.radio_left, 8, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.Control_Page2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 2, 1, 1)
        self.doubleSpinBox_range = QtGui.QDoubleSpinBox(self.Control_Page2)
        self.doubleSpinBox_range.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_range.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_range.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_range.setObjectName(_fromUtf8("doubleSpinBox_range"))
        self.gridLayout.addWidget(self.doubleSpinBox_range, 7, 3, 1, 1)
        self.pushButton_AutoContrast = QtGui.QPushButton(self.Control_Page2)
        self.pushButton_AutoContrast.setObjectName(_fromUtf8("pushButton_AutoContrast"))
        self.gridLayout.addWidget(self.pushButton_AutoContrast, 15, 1, 1, 1)
        self.doubleSpinBox_min = QtGui.QDoubleSpinBox(self.Control_Page2)
        self.doubleSpinBox_min.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_min.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_min.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_min.setObjectName(_fromUtf8("doubleSpinBox_min"))
        self.gridLayout.addWidget(self.doubleSpinBox_min, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 16, 3, 1, 1)
        self.hSliderIntensity = QtGui.QSlider(self.Control_Page2)
        self.hSliderIntensity.setProperty("value", 49)
        self.hSliderIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderIntensity.setObjectName(_fromUtf8("hSliderIntensity"))
        self.gridLayout.addWidget(self.hSliderIntensity, 2, 0, 1, 5)
        self.radio_right = QtGui.QRadioButton(self.Control_Page2)
        self.radio_right.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radio_right.setObjectName(_fromUtf8("radio_right"))
        self.gridLayout.addWidget(self.radio_right, 8, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.Control_Page2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.hSliderContrast = QtGui.QSlider(self.Control_Page2)
        self.hSliderContrast.setProperty("value", 49)
        self.hSliderContrast.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderContrast.setObjectName(_fromUtf8("hSliderContrast"))
        self.gridLayout.addWidget(self.hSliderContrast, 5, 0, 1, 5)
        self.frame_hist = QtGui.QFrame(self.Control_Page2)
        self.frame_hist.setMinimumSize(QtCore.QSize(60, 200))
        self.frame_hist.setMaximumSize(QtCore.QSize(1000, 300))
        self.frame_hist.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_hist.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_hist.setObjectName(_fromUtf8("frame_hist"))
        self.gridLayout.addWidget(self.frame_hist, 0, 0, 1, 5)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 4)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 9, 0, 1, 4)
        self.stackedWidget_control.addWidget(self.Control_Page2)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.stackedWidget_control.addWidget(self.page_4)
        self.gridLayout_2.addWidget(self.stackedWidget_control, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1277, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.toolBar.setIconSize(QtCore.QSize(35, 35))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/folder-open-128-000000.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/floppy_disk-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setVisible(True)
        self.actionSave.setIconVisibleInMenu(True)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionQuite = QtGui.QAction(MainWindow)
        self.actionQuite.setObjectName(_fromUtf8("actionQuite"))
        self.actionLeft_Right_view = QtGui.QAction(MainWindow)
        self.actionLeft_Right_view.setObjectName(_fromUtf8("actionLeft_Right_view"))
        self.action3D_view = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3D_view.setIcon(icon2)
        self.action3D_view.setObjectName(_fromUtf8("action3D_view"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp_Desk = QtGui.QAction(MainWindow)
        self.actionHelp_Desk.setObjectName(_fromUtf8("actionHelp_Desk"))
        self.actionZoom_in = QtGui.QAction(MainWindow)
        self.actionZoom_in.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/zoom-in-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon3)
        self.actionZoom_in.setObjectName(_fromUtf8("actionZoom_in"))
        self.actionZoom_out = QtGui.QAction(MainWindow)
        self.actionZoom_out.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/zoom_out-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon4)
        self.actionZoom_out.setIconText(_fromUtf8("zoom out"))
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionView_image = QtGui.QAction(MainWindow)
        self.actionView_image.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/viewimage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView_image.setIcon(icon5)
        self.actionView_image.setObjectName(_fromUtf8("actionView_image"))
        self.actionSave_all = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/saveall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_all.setIcon(icon6)
        self.actionSave_all.setObjectName(_fromUtf8("actionSave_all"))
        self.actionAdjust_Contrast = QtGui.QAction(MainWindow)
        self.actionAdjust_Contrast.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/brightcontrast.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/viewimage.png")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionAdjust_Contrast.setIcon(icon7)
        self.actionAdjust_Contrast.setObjectName(_fromUtf8("actionAdjust_Contrast"))
        self.action3D_view_2 = QtGui.QAction(MainWindow)
        self.action3D_view_2.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/444.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3D_view_2.setIcon(icon8)
        self.action3D_view_2.setObjectName(_fromUtf8("action3D_view_2"))
        self.actionAxial = QtGui.QAction(MainWindow)
        self.actionAxial.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/111.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAxial.setIcon(icon9)
        self.actionAxial.setObjectName(_fromUtf8("actionAxial"))
        self.actionSaggital = QtGui.QAction(MainWindow)
        self.actionSaggital.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/222.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaggital.setIcon(icon10)
        self.actionSaggital.setObjectName(_fromUtf8("actionSaggital"))
        self.actionCoronal = QtGui.QAction(MainWindow)
        self.actionCoronal.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/333.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCoronal.setIcon(icon11)
        self.actionCoronal.setObjectName(_fromUtf8("actionCoronal"))
        self.actionFlip_UD = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/flip1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlip_UD.setIcon(icon12)
        self.actionFlip_UD.setObjectName(_fromUtf8("actionFlip_UD"))
        self.actionFlip_LR = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/flip.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlip_LR.setIcon(icon13)
        self.actionFlip_LR.setObjectName(_fromUtf8("actionFlip_LR"))
        self.actionRot_90 = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/Toolbar/resource/rot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRot_90.setIcon(icon14)
        self.actionRot_90.setObjectName(_fromUtf8("actionRot_90"))
        self.menuHelp.addAction(self.actionHelp_Desk)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_all)
        self.menuEdit.addAction(self.actionZoom_in)
        self.menuEdit.addAction(self.actionZoom_out)
        self.menuEdit.addAction(self.actionAdjust_Contrast)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFlip_UD)
        self.menuEdit.addAction(self.actionFlip_LR)
        self.menuEdit.addAction(self.actionRot_90)
        self.menuView.addAction(self.action3D_view_2)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionAxial)
        self.menuView.addAction(self.actionSaggital)
        self.menuView.addAction(self.actionCoronal)
        self.menuView.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action3D_view_2)
        self.toolBar.addAction(self.actionAxial)
        self.toolBar.addAction(self.actionSaggital)
        self.toolBar.addAction(self.actionCoronal)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdjust_Contrast)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)

        self.retranslateUi(MainWindow)
        self.stackedWidget_image.setCurrentIndex(0)
        self.stackedWidget_control.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SITK: Susceptibility Imaging Toolkit", None))
        self.spinBox_p1_Scroll.setToolTip(_translate("MainWindow", "Scroll steps", None))
        self.spinBox_p1_Scroll.setPrefix(_translate("MainWindow", "Scroll steps: ", None))
        self.spinBox_x_3panel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>dddd</p></body></html>", None))
        self.spinBox_v_3panel.setPrefix(_translate("MainWindow", "v: ", None))
        self.lineEdit_z_2panel.setText(_translate("MainWindow", "1", None))
        self.spinBox_v_2panel.setPrefix(_translate("MainWindow", "v: ", None))
        self.spinBox_P2_scroll.setToolTip(_translate("MainWindow", "Scroll steps", None))
        self.spinBox_P2_scroll.setPrefix(_translate("MainWindow", "Scroll steps: ", None))
        self.pushButton.setText(_translate("MainWindow", "BET", None))
        self.ProcessPhase.setText(_translate("MainWindow", "Process Phase", None))
        self.QSM.setText(_translate("MainWindow", "QSM", None))
        self.radioButton_left.setText(_translate("MainWindow", "Left", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Data", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Size", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Mag", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Phase", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Real", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Imag", None))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Mask", None))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Parameters", None))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "Phase_Path", None))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "Phase_LP", None))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "TissuePhase", None))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "Frequency", None))
        self.treeWidget.topLevelItem(10).setText(0, _translate("MainWindow", "Susceptibility", None))
        self.treeWidget.topLevelItem(11).setText(0, _translate("MainWindow", "ROI", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.radioButton_right.setText(_translate("MainWindow", "Right", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Images", None))
        self.treeWidget_parameters.headerItem().setText(0, _translate("MainWindow", "Parameter", None))
        self.treeWidget_parameters.headerItem().setText(1, _translate("MainWindow", "Value", None))
        __sortingEnabled = self.treeWidget_parameters.isSortingEnabled()
        self.treeWidget_parameters.setSortingEnabled(False)
        self.treeWidget_parameters.topLevelItem(0).setText(0, _translate("MainWindow", "Acquisition", None))
        self.treeWidget_parameters.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TE1", None))
        self.treeWidget_parameters.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "4", None))
        self.treeWidget_parameters.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "voxelsize", None))
        self.treeWidget_parameters.topLevelItem(0).child(1).setText(1, _translate("MainWindow", "[ 1 1 1 ]", None))
        self.treeWidget_parameters.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "delta TE", None))
        self.treeWidget_parameters.topLevelItem(0).child(2).setText(1, _translate("MainWindow", "4", None))
        self.treeWidget_parameters.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "B0", None))
        self.treeWidget_parameters.topLevelItem(0).child(3).setText(1, _translate("MainWindow", "3", None))
        self.treeWidget_parameters.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "B0_dir", None))
        self.treeWidget_parameters.topLevelItem(0).child(4).setText(1, _translate("MainWindow", "[ 0 0 1 ]", None))
        self.treeWidget_parameters.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "Dicom", None))
        self.treeWidget_parameters.topLevelItem(0).child(4).child(1).setText(0, _translate("MainWindow", "Nii", None))
        self.treeWidget_parameters.topLevelItem(1).setText(0, _translate("MainWindow", "V_SHARP", None))
        self.treeWidget_parameters.topLevelItem(1).setText(1, _translate("MainWindow", "1", None))
        self.treeWidget_parameters.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "max_R", None))
        self.treeWidget_parameters.topLevelItem(1).child(0).setText(1, _translate("MainWindow", "30", None))
        self.treeWidget_parameters.topLevelItem(2).setText(0, _translate("MainWindow", "iHARPERELLA", None))
        self.treeWidget_parameters.topLevelItem(2).setText(1, _translate("MainWindow", "0", None))
        self.treeWidget_parameters.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "max_iter", None))
        self.treeWidget_parameters.topLevelItem(2).child(0).setText(1, _translate("MainWindow", "100", None))
        self.treeWidget_parameters.topLevelItem(3).setText(0, _translate("MainWindow", "iLSQR", None))
        self.treeWidget_parameters.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "D2_thres", None))
        self.treeWidget_parameters.topLevelItem(3).child(0).setText(1, _translate("MainWindow", "0.1", None))
        self.treeWidget_parameters.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "tol", None))
        self.treeWidget_parameters.topLevelItem(3).child(1).setText(1, _translate("MainWindow", "0.01", None))
        self.treeWidget_parameters.topLevelItem(4).setText(0, _translate("MainWindow", "Optional", None))
        self.treeWidget_parameters.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "p1", None))
        self.treeWidget_parameters.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "p2", None))
        self.treeWidget_parameters.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Parameters", None))
        self.label_4.setText(_translate("MainWindow", "mid", None))
        self.pushButton_opened.setText(_translate("MainWindow", "OK", None))
        self.label_5.setText(_translate("MainWindow", "max", None))
        self.radio_left.setText(_translate("MainWindow", "Left", None))
        self.label_6.setText(_translate("MainWindow", "range", None))
        self.pushButton_AutoContrast.setText(_translate("MainWindow", "Auto", None))
        self.radio_right.setText(_translate("MainWindow", "Right", None))
        self.label_3.setText(_translate("MainWindow", "min", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setIconText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))
        self.actionQuite.setText(_translate("MainWindow", "Exit", None))
        self.actionLeft_Right_view.setText(_translate("MainWindow", "Left-Right View", None))
        self.action3D_view.setText(_translate("MainWindow", "3D view", None))
        self.actionAbout.setText(_translate("MainWindow", "About QITK", None))
        self.actionHelp_Desk.setText(_translate("MainWindow", "Help Desk", None))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in", None))
        self.actionZoom_out.setText(_translate("MainWindow", "zoom out", None))
        self.actionView_image.setText(_translate("MainWindow", "View image", None))
        self.actionSave_all.setText(_translate("MainWindow", "Save all", None))
        self.actionAdjust_Contrast.setText(_translate("MainWindow", "Adjust Contrast", None))
        self.action3D_view_2.setText(_translate("MainWindow", "3D view", None))
        self.actionAxial.setText(_translate("MainWindow", "Axial", None))
        self.actionSaggital.setText(_translate("MainWindow", "Saggital", None))
        self.actionCoronal.setText(_translate("MainWindow", "Coronal", None))
        self.actionFlip_UD.setText(_translate("MainWindow", "flip UD", None))
        self.actionFlip_LR.setText(_translate("MainWindow", "flip LR", None))
        self.actionRot_90.setText(_translate("MainWindow", "Rot 90", None))

import QITKV0p1_rc
